#!/usr/bin/env bash
set -Eeuo pipefail

# incident_trace_analyzer.sh
# Purpose:
#   Post-cleanup forensic analyzer for multi-host /dev/shm miner incidents.
#
# It analyzes:
#   - /root/incident_cleanup_* directories generated by previous cleanup scripts
#   - cleanup.log
#   - crontab_* before/after backups
#   - quarantine malware samples
#   - login history: last, auth.log, journalctl ssh
#   - users, sudo users, SSH authorized_keys
#   - persistence residues: cron, rc.local, systemd, profile, ld.so.preload
#   - listening ports and Docker exposure
#
# This script is read-only except writing its own report directory.
#
# Usage:
#   sudo bash incident_trace_analyzer.sh
#   sudo bash incident_trace_analyzer.sh --days 30
#   sudo bash incident_trace_analyzer.sh --case-name lab-incident-20260618

DAYS=30
CASE_NAME="incident"
MAX_STRINGS_LINES=200

while [[ $# -gt 0 ]]; do
  case "$1" in
    --days)
      DAYS="${2:-30}"
      shift 2
      ;;
    --case-name)
      CASE_NAME="${2:-incident}"
      shift 2
      ;;
    --max-strings-lines)
      MAX_STRINGS_LINES="${2:-200}"
      shift 2
      ;;
    -h|--help)
      cat <<'EOF'
Usage:
  sudo bash incident_trace_analyzer.sh
  sudo bash incident_trace_analyzer.sh --days 30
  sudo bash incident_trace_analyzer.sh --case-name lab-incident-20260618

Options:
  --days N              Show recent login/auth context for approximately N days. Default: 30.
  --case-name NAME      Prefix for output report directory.
  --max-strings-lines N Max strings lines extracted from each quarantine sample. Default: 200.
EOF
      exit 0
      ;;
    *)
      echo "[FATAL] Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [[ "${EUID}" -ne 0 ]]; then
  echo "[FATAL] Please run as root: sudo bash $0"
  exit 1
fi

TS="$(date +%F_%H%M%S)"
HOST="$(hostname -f 2>/dev/null || hostname)"
OUT="/root/incident_trace_${CASE_NAME}_${HOST}_${TS}"
mkdir -p "$OUT"

MAIN="$OUT/main_report.txt"
SUMMARY="$OUT/summary.txt"
IOC="$OUT/iocs_extracted.txt"
TIMELINE="$OUT/timeline_candidates.txt"
LOGINS="$OUT/login_sources.tsv"
USERS="$OUT/users_recommended_for_rotation.txt"
QUAR="$OUT/quarantine_analysis.txt"
CURRENT="$OUT/current_state.txt"

exec > >(tee -a "$MAIN") 2>&1

say() {
  echo "[$(date +%F_%T)] $*"
}

section() {
  echo
  echo "==================== $* ===================="
}

write_file_header() {
  local f="$1"
  local title="$2"
  {
    echo "==================== $title ===================="
    echo "Host: $HOST"
    echo "Generated: $(date)"
    echo "Generated UTC: $(date -u)"
    echo
  } > "$f"
}

append() {
  local f="$1"
  shift
  echo "$*" >> "$f"
}

PATTERN_CORE='/dev/shm|xmrig|kinsing|kdevtmpfsi|cryptonight|cryptonote|monero|minexmr|nanopool|stratum|\.kw|kwo.*rke|k.*worker|logger-'
PATTERN_PERSIST='/dev/shm|xmrig|kinsing|kdevtmpfsi|cryptonight|cryptonote|monero|minexmr|nanopool|stratum|base64[[:space:]]+-d|curl[[:space:]].*\|[[:space:]]*(sh|bash)|wget[[:space:]].*\|[[:space:]]*(sh|bash)|bash[[:space:]]+-c|nohup[[:space:]].*&|logger-'

write_file_header "$SUMMARY" "Incident trace summary"
write_file_header "$IOC" "Extracted IOCs"
write_file_header "$TIMELINE" "Timeline candidates"
write_file_header "$LOGINS" "Login source summary"
write_file_header "$USERS" "Users recommended for credential rotation"
write_file_header "$QUAR" "Quarantine analysis"
write_file_header "$CURRENT" "Current state"

section "0. Scope"
cat <<EOF
This is an analysis-only script.
It reads previous cleanup artifacts, login logs, SSH keys, and system state.
It does NOT remove malware and does NOT modify persistence.
Output directory:
  $OUT
EOF

section "1. System time and timezone context"
{
  echo "Hostname: $HOST"
  echo "date: $(date)"
  echo "date -u: $(date -u)"
  echo
  echo "timedatectl:"
  timedatectl 2>/dev/null || true
  echo
  echo "/etc/timezone:"
  cat /etc/timezone 2>/dev/null || true
  echo
  echo "TZ=UTC last -F -a | head -20:"
  TZ=UTC last -F -a 2>/dev/null | head -20 || true
  echo
  echo "TZ=Asia/Shanghai last -F -a | head -20:"
  TZ=Asia/Shanghai last -F -a 2>/dev/null | head -20 || true
} | tee "$OUT/timezone_context.txt"

cat >> "$SUMMARY" <<EOF

[Time zone note]
- Linux 'last' output is rendered in the timezone of the command environment.
- This script records both UTC and Asia/Shanghai rendering for comparison.
- When correlating with Zabbix, compare Zabbix frontend timezone, Zabbix server timezone, and host timezone.
EOF

section "2. Locate cleanup artifact directories"
CLEANUP_DIRS="$(find /root -maxdepth 1 -type d -name 'incident_cleanup_*' -printf '%T@ %TY-%Tm-%Td %TH:%TM:%TS %p\n' 2>/dev/null | sort -n || true)"
if [[ -z "$CLEANUP_DIRS" ]]; then
  echo "No /root/incident_cleanup_* directories found."
  append "$SUMMARY" "Cleanup artifact directories: none found"
else
  echo "$CLEANUP_DIRS" | tee "$OUT/cleanup_dirs.txt"
  append "$SUMMARY" "Cleanup artifact directories found:"
  echo "$CLEANUP_DIRS" >> "$SUMMARY"
fi

section "3. Inventory cleanup artifacts"
find /root -maxdepth 3 -path '/root/incident_cleanup_*' -o -path '/root/incident_cleanup_*/*' 2>/dev/null \
  -printf '%TY-%Tm-%Td %TH:%TM:%TS %M %u %g %s %p\n' \
  | sort | tee "$OUT/cleanup_artifact_inventory.txt" || true

section "4. Extract IOCs from cleanup logs and backups"
{
  echo "---- cleanup.log IOC hits ----"
  grep -RInE "$PATTERN_CORE|PID|cmdline|exe|Quarantine|Suspicious|crontab|rc.local|systemd|Final status|STATUS" \
    /root/incident_cleanup_*/cleanup.log 2>/dev/null || true

  echo
  echo "---- crontab before/after IOC hits ----"
  grep -RInE "$PATTERN_CORE|curl|wget|base64|bash|nohup" \
    /root/incident_cleanup_*/crontab_* 2>/dev/null || true

  echo
  echo "---- backup IOC hits ----"
  grep -RInE "$PATTERN_CORE|curl|wget|base64|bash|nohup" \
    /root/incident_cleanup_*/backup* 2>/dev/null || true
} | tee -a "$IOC"

section "5. Build timeline candidates from cleanup artifacts"
{
  echo "---- cleanup directory mtimes ----"
  find /root -maxdepth 1 -type d -name 'incident_cleanup_*' -printf '%TY-%Tm-%Td %TH:%TM:%TS DIR %p\n' 2>/dev/null | sort || true

  echo
  echo "---- cleanup files mtimes ----"
  find /root/incident_cleanup_* -maxdepth 3 -type f -printf '%TY-%Tm-%Td %TH:%TM:%TS FILE %p\n' 2>/dev/null | sort || true

  echo
  echo "---- suspicious lines with line numbers ----"
  grep -RInE "$PATTERN_CORE|root cron|crontab|rc.local|systemd|Quarantine|Killing|Remaining suspicious|Initial IOC|Final status|STATUS" \
    /root/incident_cleanup_* 2>/dev/null || true
} | tee -a "$TIMELINE"

section "6. Analyze quarantine samples"
if find /root/incident_cleanup_* -path '*/quarantine/*' -type f 2>/dev/null | grep -q .; then
  while IFS= read -r f; do
    {
      echo
      echo "==================== SAMPLE: $f ===================="
      echo "stat:"
      stat "$f" 2>/dev/null || true
      echo
      echo "file:"
      file "$f" 2>/dev/null || true
      echo
      echo "sha256:"
      sha256sum "$f" 2>/dev/null || true
      echo
      echo "permissions:"
      ls -lah "$f" 2>/dev/null || true
      echo
      echo "strings IOC subset:"
      strings -a "$f" 2>/dev/null \
        | grep -Ei 'http|https|stratum|pool|xmrig|monero|wallet|passwd|authorized|ssh|curl|wget|/dev/shm|/tmp|cron|systemd|kinsing|kdevtmp|linux|x86|gcc|go build' \
        | head -"$MAX_STRINGS_LINES" || true
      echo
      echo "strings first ${MAX_STRINGS_LINES} lines:"
      strings -a "$f" 2>/dev/null | head -"$MAX_STRINGS_LINES" || true
    } >> "$QUAR"
  done < <(find /root/incident_cleanup_* -path '*/quarantine/*' -type f 2>/dev/null | sort)
else
  echo "No quarantine samples found." | tee -a "$QUAR"
fi

section "7. Current runtime verification"
{
  echo "---- current /dev/shm ----"
  ls -lah /dev/shm 2>/dev/null || true
  find /dev/shm -maxdepth 1 \( -type f -o -type l \) -ls 2>/dev/null || true

  echo
  echo "---- current suspicious processes ----"
  ps -eo pid,ppid,user,%cpu,%mem,etime,cmd \
    | grep -E "$PATTERN_CORE" \
    | grep -v grep || echo "clean"

  echo
  echo "---- current cron persistence ----"
  grep -RInE "$PATTERN_PERSIST" \
    /etc/crontab /etc/cron.d /etc/cron.hourly /etc/cron.daily /etc/cron.weekly /etc/cron.monthly \
    /var/spool/cron /var/spool/cron/crontabs 2>/dev/null || echo "clean"

  echo
  echo "---- current rc.local/profile persistence ----"
  grep -RInE "$PATTERN_PERSIST" \
    /etc/rc.local /etc/init.d /etc/profile /etc/bash.bashrc /etc/profile.d /etc/ssh/sshrc \
    /root/.bashrc /root/.profile /root/.ssh/rc /home/*/.bashrc /home/*/.profile /home/*/.ssh/rc \
    2>/dev/null | grep -Ev '/etc/init.d/udev|/root/incident_cleanup_|/tmp/cron_' || echo "clean"

  echo
  echo "---- current systemd persistence ----"
  grep -RInE "$PATTERN_PERSIST" \
    /etc/systemd/system /lib/systemd/system /usr/lib/systemd/system \
    2>/dev/null | grep -Ev '/root/incident_cleanup_|/tmp/cron_' || echo "clean"

  echo
  echo "---- current /dev/shm mount ----"
  mount | grep ' /dev/shm ' || true
} | tee -a "$CURRENT"

section "8. Login history and source IP analysis"
{
  echo -e "count\tuser\tsource"
  last -F -w -a 2>/dev/null \
    | awk '
      NF>=1 && $1 !~ /^(reboot|wtmp|shutdown)$/ {
        user=$1;
        src=$NF;
        if (src ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ || src ~ /:/ || src ~ /^[A-Za-z0-9_.-]+$/) {
          key=user "\t" src;
          c[key]++;
        }
      }
      END {
        for (k in c) print c[k] "\t" k;
      }
    ' | sort -nr
} | tee "$LOGINS"

{
  echo
  echo "---- last -F -a head -100 ----"
  last -F -w -a 2>/dev/null | head -100 || true

  echo
  echo "---- last rendered in UTC ----"
  TZ=UTC last -F -w -a 2>/dev/null | head -100 || true

  echo
  echo "---- last rendered in Asia/Shanghai ----"
  TZ=Asia/Shanghai last -F -w -a 2>/dev/null | head -100 || true
} | tee "$OUT/last_history.txt"

section "9. Auth log SSH analysis"
{
  echo "---- Accepted SSH logins ----"
  zgrep -hEi 'Accepted password|Accepted publickey|Accepted keyboard-interactive' /var/log/auth.log* /var/log/secure* 2>/dev/null || true

  echo
  echo "---- Failed/Invalid SSH attempts, tail 500 ----"
  zgrep -hEi 'Failed password|Invalid user|authentication failure|maximum authentication attempts|POSSIBLE BREAK-IN' \
    /var/log/auth.log* /var/log/secure* 2>/dev/null | tail -500 || true

  echo
  echo "---- sudo/su/crontab auth events, tail 500 ----"
  zgrep -hEi 'sudo:|su:|crontab|session opened for user root|COMMAND=' \
    /var/log/auth.log* /var/log/secure* 2>/dev/null | tail -500 || true
} | tee "$OUT/auth_ssh_events.txt"

{
  echo -e "count\tuser\tip\tauth_method"
  zgrep -hEi 'Accepted password|Accepted publickey|Accepted keyboard-interactive' /var/log/auth.log* /var/log/secure* 2>/dev/null \
    | awk '
      {
        method="unknown";
        if ($0 ~ /Accepted password/) method="password";
        if ($0 ~ /Accepted publickey/) method="publickey";
        if ($0 ~ /keyboard-interactive/) method="keyboard-interactive";
        user="unknown"; ip="unknown";
        for (i=1;i<=NF;i++) {
          if ($i=="for") user=$(i+1);
          if ($i=="from") ip=$(i+1);
        }
        key=user "\t" ip "\t" method;
        c[key]++;
      }
      END {for (k in c) print c[k] "\t" k;}
    ' | sort -nr
} | tee "$OUT/accepted_ssh_summary.tsv"

section "10. User and credential exposure analysis"
{
  echo "---- UID 0 users ----"
  awk -F: '$3==0 {print}' /etc/passwd || true

  echo
  echo "---- login-capable users ----"
  awk -F: '$7 !~ /(nologin|false)$/ {printf "%-24s uid=%-8s shell=%s home=%s\n",$1,$3,$7,$6}' /etc/passwd || true

  echo
  echo "---- sudo/wheel/admin groups ----"
  getent group sudo 2>/dev/null || true
  getent group wheel 2>/dev/null || true
  getent group admin 2>/dev/null || true

  echo
  echo "---- users with non-locked password hash ----"
  if [[ -r /etc/shadow ]]; then
    awk -F: '($2 != "!" && $2 != "*" && $2 !~ /^!/ && length($2)>0) {print $1}' /etc/shadow | sort -u
  fi

  echo
  echo "---- authorized_keys files ----"
  find /root /home -path '*/.ssh/authorized_keys' -type f \
    -exec echo "### {}" \; \
    -exec sh -c 'ls -lah "$1"; wc -l "$1"; sed -n "1,10p" "$1"' sh {} \; 2>/dev/null || true
} | tee "$OUT/users_and_keys.txt"

{
  {
    awk -F: '$3==0 {print $1}' /etc/passwd 2>/dev/null
    awk -F: '$7 !~ /(nologin|false)$/ {print $1}' /etc/passwd 2>/dev/null
    if [[ -r /etc/shadow ]]; then
      awk -F: '($2 != "!" && $2 != "*" && $2 !~ /^!/ && length($2)>0) {print $1}' /etc/shadow
    fi
    find /root /home -path '*/.ssh/authorized_keys' -type f -printf '%h\n' 2>/dev/null \
      | sed -E 's#/.ssh$##; s#^/home/##; s#^/root$#root#'
    getent group sudo 2>/dev/null | awk -F: '{print $4}' | tr ',' '\n'
    getent group wheel 2>/dev/null | awk -F: '{print $4}' | tr ',' '\n'
    last -w 2>/dev/null | awk 'NF>=1 && $1 !~ /^(reboot|wtmp|shutdown)$/ {print $1}' | head -200
  } | sed '/^$/d' | sort -u
} | tee -a "$USERS"

section "11. Network exposure and active connections"
{
  echo "---- ss -tulpen ----"
  ss -tulpen 2>/dev/null || true

  echo
  echo "---- ss -tunap, first 300 ----"
  ss -tunap 2>/dev/null | head -300 || true

  echo
  echo "---- outbound established connections ----"
  ss -tunap 2>/dev/null \
    | awk '$1=="tcp" && $2=="ESTAB" {print}' \
    | head -300 || true

  echo
  echo "---- peer summary ----"
  ss -tunap 2>/dev/null \
    | awk 'NR>1 {print $5}' \
    | sed 's/^\[//; s/\]$//;' \
    | sort | uniq -c | sort -nr | head -100
} | tee "$OUT/network_state.txt"

section "12. Docker and container exposure"
{
  if command -v docker >/dev/null 2>&1; then
    echo "---- docker ps ----"
    docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}" || true

    echo
    echo "---- docker inspect risky fields ----"
    if [[ -n "$(docker ps -q 2>/dev/null || true)" ]]; then
      docker inspect $(docker ps -q) --format '### {{.Name}}
Image={{.Config.Image}}
Privileged={{.HostConfig.Privileged}}
Network={{.HostConfig.NetworkMode}}
PidMode={{.HostConfig.PidMode}}
User={{.Config.User}}
Entrypoint={{json .Config.Entrypoint}}
Cmd={{json .Config.Cmd}}
Mounts={{json .Mounts}}
Env={{json .Config.Env}}
' 2>/dev/null || true
    else
      echo "No running containers."
    fi
  else
    echo "Docker not installed."
  fi
} | tee "$OUT/docker_state.txt"

section "13. frps / panel / remote access service analysis"
{
  echo "---- service status quick check ----"
  for svc in frps frpc 1panel bt nginx apache2 httpd xrdp anydesk vncserver tigervncserver zabbix-server zabbix-agent; do
    systemctl is-active "$svc" >/dev/null 2>&1 && echo "$svc active" || true
  done

  echo
  echo "---- frp files ----"
  find /etc /opt /usr/local /root /home -maxdepth 5 \
    \( -iname '*frps*' -o -iname '*frpc*' -o -iname '*frp*.ini' -o -iname '*frp*.toml' \) \
    -printf '%TY-%Tm-%Td %TH:%TM %M %u %g %s %p\n' 2>/dev/null | sort || true

  echo
  echo "---- panel-related files ----"
  find /www /opt /usr/local /root -maxdepth 4 \
    \( -iname '*1panel*' -o -iname '*bt*' -o -iname '*panel*' \) \
    -printf '%TY-%Tm-%Td %TH:%TM %M %u %g %s %p\n' 2>/dev/null | head -200 || true
} | tee "$OUT/frp_panel_remote_services.txt"

section "14. Produce human-readable summary"
CURRENT_PROC_HITS="$(ps -eo pid,ppid,user,%cpu,%mem,etime,cmd | grep -E "$PATTERN_CORE" | grep -v grep || true)"
CURRENT_PERSIST_HITS="$(grep -RInE "$PATTERN_PERSIST" \
  /etc/crontab /etc/cron.d /etc/cron.hourly /etc/cron.daily /etc/cron.weekly /etc/cron.monthly \
  /var/spool/cron /var/spool/cron/crontabs \
  /etc/rc.local /etc/init.d /etc/profile /etc/bash.bashrc /etc/profile.d /etc/ssh/sshrc \
  /etc/systemd/system /lib/systemd/system /usr/lib/systemd/system \
  2>/dev/null | grep -Ev '/etc/init.d/udev|/root/incident_cleanup_|/tmp/cron_' || true)"
SHM_FILES="$(find /dev/shm -maxdepth 1 \( -type f -o -type l \) -ls 2>/dev/null || true)"
CLEANUP_COUNT="$(find /root -maxdepth 1 -type d -name 'incident_cleanup_*' 2>/dev/null | wc -l | tr -d ' ')"
QUAR_COUNT="$(find /root/incident_cleanup_* -path '*/quarantine/*' -type f 2>/dev/null | wc -l | tr -d ' ')"
SSH_TOP="$(tail -n +2 "$LOGINS" 2>/dev/null | head -10 || true)"

{
  echo "Host: $HOST"
  echo "Generated: $(date)"
  echo "Generated UTC: $(date -u)"
  echo
  echo "Cleanup artifact dirs: $CLEANUP_COUNT"
  echo "Quarantine samples: $QUAR_COUNT"
  echo
  echo "Current suspicious process state:"
  if [[ -n "$CURRENT_PROC_HITS" ]]; then
    echo "  WARNING: suspicious processes currently found"
    echo "$CURRENT_PROC_HITS" | sed 's/^/    /'
  else
    echo "  clean"
  fi
  echo
  echo "Current persistence state:"
  if [[ -n "$CURRENT_PERSIST_HITS" ]]; then
    echo "  WARNING: suspicious persistence currently found"
    echo "$CURRENT_PERSIST_HITS" | sed 's/^/    /'
  else
    echo "  clean"
  fi
  echo
  echo "/dev/shm current files/symlinks:"
  if [[ -n "$SHM_FILES" ]]; then
    echo "$SHM_FILES" | sed 's/^/    /'
  else
    echo "  clean"
  fi
  echo
  echo "Top login user/source pairs:"
  echo "$SSH_TOP" | sed 's/^/  /'
  echo
  echo "Users recommended for password/key rotation:"
  sed 's/^/  - /' "$USERS"
  echo
  echo "Important output files:"
  echo "  $MAIN"
  echo "  $SUMMARY"
  echo "  $IOC"
  echo "  $TIMELINE"
  echo "  $LOGINS"
  echo "  $OUT/accepted_ssh_summary.tsv"
  echo "  $OUT/auth_ssh_events.txt"
  echo "  $OUT/network_state.txt"
  echo "  $OUT/docker_state.txt"
  echo "  $OUT/frp_panel_remote_services.txt"
  echo "  $QUAR"
} | tee "$SUMMARY"

echo
echo "============================================================"
echo "Analysis done."
echo "Output directory:"
echo "  $OUT"
echo
echo "Main summary:"
echo "  $SUMMARY"
echo
echo "Recommended next step:"
echo "  tar czf /tmp/incident_trace_${HOST}_${TS}.tar.gz -C $(dirname "$OUT") $(basename "$OUT")"
echo "============================================================"